/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as App403RouteImport } from './routes/_app/403'
import { Route as AppAccountingRouteImport } from './routes/_app/accounting'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppPurchasingRouteImport } from './routes/_app/purchasing'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppInventoryProductsRouteImport } from './routes/_app/inventory/products'
import { Route as AppInventoryStockLevelsRouteImport } from './routes/_app/inventory/stock-levels'
import { Route as AppInventoryStockMovementsRouteImport } from './routes/_app/inventory/stock-movements'
import { Route as AppInventoryProductsIndexRouteImport } from './routes/_app/inventory/products/index'
import { Route as AppInventoryProductsProductIdRouteImport } from './routes/_app/inventory/products/$productId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const App403Route = App403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasingRoute = AppPurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryProductsRoute = AppInventoryProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryStockLevelsRoute = AppInventoryStockLevelsRouteImport.update({
  id: '/stock-levels',
  path: '/stock-levels',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryStockMovementsRoute =
  AppInventoryStockMovementsRouteImport.update({
    id: '/stock-movements',
    path: '/stock-movements',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryProductsIndexRoute =
  AppInventoryProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppInventoryProductsRoute,
  } as any)
const AppInventoryProductsProductIdRoute =
  AppInventoryProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AppInventoryProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/403': typeof App403Route
  '/accounting': typeof AppAccountingRoute
  '/admin': typeof AppAdminRoute
  '/approvals': typeof AppApprovalsRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/purchasing': typeof AppPurchasingRoute
  '/sales': typeof AppSalesRoute
  '/login': typeof AuthLoginRoute
  '/inventory/products': typeof AppInventoryProductsRouteWithChildren
  '/inventory/stock-levels': typeof AppInventoryStockLevelsRoute
  '/inventory/stock-movements': typeof AppInventoryStockMovementsRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/inventory/products/$productId': typeof AppInventoryProductsProductIdRoute
  '/inventory/products/': typeof AppInventoryProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/403': typeof App403Route
  '/accounting': typeof AppAccountingRoute
  '/admin': typeof AppAdminRoute
  '/approvals': typeof AppApprovalsRoute
  '/purchasing': typeof AppPurchasingRoute
  '/sales': typeof AppSalesRoute
  '/login': typeof AuthLoginRoute
  '/inventory/stock-levels': typeof AppInventoryStockLevelsRoute
  '/inventory/stock-movements': typeof AppInventoryStockMovementsRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/inventory/products/$productId': typeof AppInventoryProductsProductIdRoute
  '/inventory/products': typeof AppInventoryProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/403': typeof App403Route
  '/_app/accounting': typeof AppAccountingRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/purchasing': typeof AppPurchasingRoute
  '/_app/sales': typeof AppSalesRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/inventory/products': typeof AppInventoryProductsRouteWithChildren
  '/_app/inventory/stock-levels': typeof AppInventoryStockLevelsRoute
  '/_app/inventory/stock-movements': typeof AppInventoryStockMovementsRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/inventory/products/$productId': typeof AppInventoryProductsProductIdRoute
  '/_app/inventory/products/': typeof AppInventoryProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/accounting'
    | '/admin'
    | '/approvals'
    | '/inventory'
    | '/purchasing'
    | '/sales'
    | '/login'
    | '/inventory/products'
    | '/inventory/stock-levels'
    | '/inventory/stock-movements'
    | '/inventory/'
    | '/inventory/products/$productId'
    | '/inventory/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/accounting'
    | '/admin'
    | '/approvals'
    | '/purchasing'
    | '/sales'
    | '/login'
    | '/inventory/stock-levels'
    | '/inventory/stock-movements'
    | '/inventory'
    | '/inventory/products/$productId'
    | '/inventory/products'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/403'
    | '/_app/accounting'
    | '/_app/admin'
    | '/_app/approvals'
    | '/_app/inventory'
    | '/_app/purchasing'
    | '/_app/sales'
    | '/_auth/login'
    | '/_app/'
    | '/_app/inventory/products'
    | '/_app/inventory/stock-levels'
    | '/_app/inventory/stock-movements'
    | '/_app/inventory/'
    | '/_app/inventory/products/$productId'
    | '/_app/inventory/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/403': {
      id: '/_app/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof App403RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchasing': {
      id: '/_app/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof AppPurchasingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/products': {
      id: '/_app/inventory/products'
      path: '/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof AppInventoryProductsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/stock-levels': {
      id: '/_app/inventory/stock-levels'
      path: '/stock-levels'
      fullPath: '/inventory/stock-levels'
      preLoaderRoute: typeof AppInventoryStockLevelsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/stock-movements': {
      id: '/_app/inventory/stock-movements'
      path: '/stock-movements'
      fullPath: '/inventory/stock-movements'
      preLoaderRoute: typeof AppInventoryStockMovementsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/products/': {
      id: '/_app/inventory/products/'
      path: '/'
      fullPath: '/inventory/products/'
      preLoaderRoute: typeof AppInventoryProductsIndexRouteImport
      parentRoute: typeof AppInventoryProductsRoute
    }
    '/_app/inventory/products/$productId': {
      id: '/_app/inventory/products/$productId'
      path: '/$productId'
      fullPath: '/inventory/products/$productId'
      preLoaderRoute: typeof AppInventoryProductsProductIdRouteImport
      parentRoute: typeof AppInventoryProductsRoute
    }
  }
}

interface AppInventoryProductsRouteChildren {
  AppInventoryProductsProductIdRoute: typeof AppInventoryProductsProductIdRoute
  AppInventoryProductsIndexRoute: typeof AppInventoryProductsIndexRoute
}

const AppInventoryProductsRouteChildren: AppInventoryProductsRouteChildren = {
  AppInventoryProductsProductIdRoute: AppInventoryProductsProductIdRoute,
  AppInventoryProductsIndexRoute: AppInventoryProductsIndexRoute,
}

const AppInventoryProductsRouteWithChildren =
  AppInventoryProductsRoute._addFileChildren(AppInventoryProductsRouteChildren)

interface AppInventoryRouteChildren {
  AppInventoryProductsRoute: typeof AppInventoryProductsRouteWithChildren
  AppInventoryStockLevelsRoute: typeof AppInventoryStockLevelsRoute
  AppInventoryStockMovementsRoute: typeof AppInventoryStockMovementsRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryProductsRoute: AppInventoryProductsRouteWithChildren,
  AppInventoryStockLevelsRoute: AppInventoryStockLevelsRoute,
  AppInventoryStockMovementsRoute: AppInventoryStockMovementsRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppRouteChildren {
  App403Route: typeof App403Route
  AppAccountingRoute: typeof AppAccountingRoute
  AppAdminRoute: typeof AppAdminRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppPurchasingRoute: typeof AppPurchasingRoute
  AppSalesRoute: typeof AppSalesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  App403Route: App403Route,
  AppAccountingRoute: AppAccountingRoute,
  AppAdminRoute: AppAdminRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppPurchasingRoute: AppPurchasingRoute,
  AppSalesRoute: AppSalesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
