/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as App403RouteImport } from './routes/_app/403'
import { Route as AppAccountingRouteImport } from './routes/_app/accounting'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppHrmRouteImport } from './routes/_app/hrm'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppPurchasingRouteImport } from './routes/_app/purchasing'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppAccountingIndexRouteImport } from './routes/_app/accounting/index'
import { Route as AppAccountingApAgingRouteImport } from './routes/_app/accounting/ap-aging'
import { Route as AppAccountingArAgingRouteImport } from './routes/_app/accounting/ar-aging'
import { Route as AppAccountingChartOfAccountsRouteImport } from './routes/_app/accounting/chart-of-accounts'
import { Route as AppAccountingGeneralLedgerRouteImport } from './routes/_app/accounting/general-ledger'
import { Route as AppAccountingTrialBalanceRouteImport } from './routes/_app/accounting/trial-balance'
import { Route as AppHrmIndexRouteImport } from './routes/_app/hrm/index'
import { Route as AppHrmLeaveRouteImport } from './routes/_app/hrm/leave'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppInventoryProductsRouteImport } from './routes/_app/inventory/products'
import { Route as AppInventoryStockLevelsRouteImport } from './routes/_app/inventory/stock-levels'
import { Route as AppInventoryStockMovementsRouteImport } from './routes/_app/inventory/stock-movements'
import { Route as AppPurchasingIndexRouteImport } from './routes/_app/purchasing/index'
import { Route as AppPurchasingBillsRouteImport } from './routes/_app/purchasing/bills'
import { Route as AppPurchasingOrdersRouteImport } from './routes/_app/purchasing/orders'
import { Route as AppPurchasingSuppliersRouteImport } from './routes/_app/purchasing/suppliers'
import { Route as AppSalesIndexRouteImport } from './routes/_app/sales/index'
import { Route as AppSalesCustomersRouteImport } from './routes/_app/sales/customers'
import { Route as AppSalesInvoicesRouteImport } from './routes/_app/sales/invoices'
import { Route as AppSalesOrdersRouteImport } from './routes/_app/sales/orders'
import { Route as AppSalesQuotationsRouteImport } from './routes/_app/sales/quotations'
import { Route as AppHrmLeaveIndexRouteImport } from './routes/_app/hrm/leave/index'
import { Route as AppHrmLeaveNewRouteImport } from './routes/_app/hrm/leave/new'
import { Route as AppInventoryProductsIndexRouteImport } from './routes/_app/inventory/products/index'
import { Route as AppInventoryProductsProductIdRouteImport } from './routes/_app/inventory/products/$productId'
import { Route as AppPurchasingBillsIndexRouteImport } from './routes/_app/purchasing/bills/index'
import { Route as AppPurchasingBillsBillIdRouteImport } from './routes/_app/purchasing/bills/$billId'
import { Route as AppPurchasingBillsNewRouteImport } from './routes/_app/purchasing/bills/new'
import { Route as AppPurchasingOrdersIndexRouteImport } from './routes/_app/purchasing/orders/index'
import { Route as AppPurchasingOrdersNewRouteImport } from './routes/_app/purchasing/orders/new'
import { Route as AppSalesInvoicesIndexRouteImport } from './routes/_app/sales/invoices/index'
import { Route as AppSalesOrdersIndexRouteImport } from './routes/_app/sales/orders/index'
import { Route as AppSalesQuotationsIndexRouteImport } from './routes/_app/sales/quotations/index'
import { Route as AppSalesQuotationsQuotationIdRouteImport } from './routes/_app/sales/quotations/$quotationId'
import { Route as AppSalesQuotationsNewRouteImport } from './routes/_app/sales/quotations/new'
import { Route as AppHrmLeaveLeaveIdIndexRouteImport } from './routes/_app/hrm/leave/$leaveId/index'
import { Route as AppHrmLeaveLeaveIdEditRouteImport } from './routes/_app/hrm/leave/$leaveId/edit'
import { Route as AppPurchasingOrdersPoIdIndexRouteImport } from './routes/_app/purchasing/orders/$poId/index'
import { Route as AppPurchasingOrdersPoIdReceiveRouteImport } from './routes/_app/purchasing/orders/$poId/receive'
import { Route as AppSalesInvoicesInvoiceIdIndexRouteImport } from './routes/_app/sales/invoices/$invoiceId/index'
import { Route as AppSalesInvoicesInvoiceIdPreviewRouteImport } from './routes/_app/sales/invoices/$invoiceId/preview'
import { Route as AppSalesOrdersSoIdIndexRouteImport } from './routes/_app/sales/orders/$soId/index'
import { Route as AppSalesOrdersSoIdDeliverRouteImport } from './routes/_app/sales/orders/$soId/deliver'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const App403Route = App403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppHrmRoute = AppHrmRouteImport.update({
  id: '/hrm',
  path: '/hrm',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasingRoute = AppPurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppAccountingIndexRoute = AppAccountingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountingRoute,
} as any)
const AppAccountingApAgingRoute = AppAccountingApAgingRouteImport.update({
  id: '/ap-aging',
  path: '/ap-aging',
  getParentRoute: () => AppAccountingRoute,
} as any)
const AppAccountingArAgingRoute = AppAccountingArAgingRouteImport.update({
  id: '/ar-aging',
  path: '/ar-aging',
  getParentRoute: () => AppAccountingRoute,
} as any)
const AppAccountingChartOfAccountsRoute =
  AppAccountingChartOfAccountsRouteImport.update({
    id: '/chart-of-accounts',
    path: '/chart-of-accounts',
    getParentRoute: () => AppAccountingRoute,
  } as any)
const AppAccountingGeneralLedgerRoute =
  AppAccountingGeneralLedgerRouteImport.update({
    id: '/general-ledger',
    path: '/general-ledger',
    getParentRoute: () => AppAccountingRoute,
  } as any)
const AppAccountingTrialBalanceRoute =
  AppAccountingTrialBalanceRouteImport.update({
    id: '/trial-balance',
    path: '/trial-balance',
    getParentRoute: () => AppAccountingRoute,
  } as any)
const AppHrmIndexRoute = AppHrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHrmRoute,
} as any)
const AppHrmLeaveRoute = AppHrmLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppHrmRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryProductsRoute = AppInventoryProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryStockLevelsRoute = AppInventoryStockLevelsRouteImport.update({
  id: '/stock-levels',
  path: '/stock-levels',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryStockMovementsRoute =
  AppInventoryStockMovementsRouteImport.update({
    id: '/stock-movements',
    path: '/stock-movements',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppPurchasingIndexRoute = AppPurchasingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPurchasingRoute,
} as any)
const AppPurchasingBillsRoute = AppPurchasingBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppPurchasingRoute,
} as any)
const AppPurchasingOrdersRoute = AppPurchasingOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppPurchasingRoute,
} as any)
const AppPurchasingSuppliersRoute = AppPurchasingSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppPurchasingRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesCustomersRoute = AppSalesCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesInvoicesRoute = AppSalesInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesOrdersRoute = AppSalesOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesQuotationsRoute = AppSalesQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppHrmLeaveIndexRoute = AppHrmLeaveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHrmLeaveRoute,
} as any)
const AppHrmLeaveNewRoute = AppHrmLeaveNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppHrmLeaveRoute,
} as any)
const AppInventoryProductsIndexRoute =
  AppInventoryProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppInventoryProductsRoute,
  } as any)
const AppInventoryProductsProductIdRoute =
  AppInventoryProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AppInventoryProductsRoute,
  } as any)
const AppPurchasingBillsIndexRoute = AppPurchasingBillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPurchasingBillsRoute,
} as any)
const AppPurchasingBillsBillIdRoute =
  AppPurchasingBillsBillIdRouteImport.update({
    id: '/$billId',
    path: '/$billId',
    getParentRoute: () => AppPurchasingBillsRoute,
  } as any)
const AppPurchasingBillsNewRoute = AppPurchasingBillsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPurchasingBillsRoute,
} as any)
const AppPurchasingOrdersIndexRoute =
  AppPurchasingOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPurchasingOrdersRoute,
  } as any)
const AppPurchasingOrdersNewRoute = AppPurchasingOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPurchasingOrdersRoute,
} as any)
const AppSalesInvoicesIndexRoute = AppSalesInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesInvoicesRoute,
} as any)
const AppSalesOrdersIndexRoute = AppSalesOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesOrdersRoute,
} as any)
const AppSalesQuotationsIndexRoute = AppSalesQuotationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesQuotationsRoute,
} as any)
const AppSalesQuotationsQuotationIdRoute =
  AppSalesQuotationsQuotationIdRouteImport.update({
    id: '/$quotationId',
    path: '/$quotationId',
    getParentRoute: () => AppSalesQuotationsRoute,
  } as any)
const AppSalesQuotationsNewRoute = AppSalesQuotationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSalesQuotationsRoute,
} as any)
const AppHrmLeaveLeaveIdIndexRoute = AppHrmLeaveLeaveIdIndexRouteImport.update({
  id: '/$leaveId/',
  path: '/$leaveId/',
  getParentRoute: () => AppHrmLeaveRoute,
} as any)
const AppHrmLeaveLeaveIdEditRoute = AppHrmLeaveLeaveIdEditRouteImport.update({
  id: '/$leaveId/edit',
  path: '/$leaveId/edit',
  getParentRoute: () => AppHrmLeaveRoute,
} as any)
const AppPurchasingOrdersPoIdIndexRoute =
  AppPurchasingOrdersPoIdIndexRouteImport.update({
    id: '/$poId/',
    path: '/$poId/',
    getParentRoute: () => AppPurchasingOrdersRoute,
  } as any)
const AppPurchasingOrdersPoIdReceiveRoute =
  AppPurchasingOrdersPoIdReceiveRouteImport.update({
    id: '/$poId/receive',
    path: '/$poId/receive',
    getParentRoute: () => AppPurchasingOrdersRoute,
  } as any)
const AppSalesInvoicesInvoiceIdIndexRoute =
  AppSalesInvoicesInvoiceIdIndexRouteImport.update({
    id: '/$invoiceId/',
    path: '/$invoiceId/',
    getParentRoute: () => AppSalesInvoicesRoute,
  } as any)
const AppSalesInvoicesInvoiceIdPreviewRoute =
  AppSalesInvoicesInvoiceIdPreviewRouteImport.update({
    id: '/$invoiceId/preview',
    path: '/$invoiceId/preview',
    getParentRoute: () => AppSalesInvoicesRoute,
  } as any)
const AppSalesOrdersSoIdIndexRoute = AppSalesOrdersSoIdIndexRouteImport.update({
  id: '/$soId/',
  path: '/$soId/',
  getParentRoute: () => AppSalesOrdersRoute,
} as any)
const AppSalesOrdersSoIdDeliverRoute =
  AppSalesOrdersSoIdDeliverRouteImport.update({
    id: '/$soId/deliver',
    path: '/$soId/deliver',
    getParentRoute: () => AppSalesOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/403': typeof App403Route
  '/accounting': typeof AppAccountingRouteWithChildren
  '/admin': typeof AppAdminRoute
  '/approvals': typeof AppApprovalsRoute
  '/hrm': typeof AppHrmRouteWithChildren
  '/inventory': typeof AppInventoryRouteWithChildren
  '/purchasing': typeof AppPurchasingRouteWithChildren
  '/sales': typeof AppSalesRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/accounting/ap-aging': typeof AppAccountingApAgingRoute
  '/accounting/ar-aging': typeof AppAccountingArAgingRoute
  '/accounting/chart-of-accounts': typeof AppAccountingChartOfAccountsRoute
  '/accounting/general-ledger': typeof AppAccountingGeneralLedgerRoute
  '/accounting/trial-balance': typeof AppAccountingTrialBalanceRoute
  '/hrm/leave': typeof AppHrmLeaveRouteWithChildren
  '/inventory/products': typeof AppInventoryProductsRouteWithChildren
  '/inventory/stock-levels': typeof AppInventoryStockLevelsRoute
  '/inventory/stock-movements': typeof AppInventoryStockMovementsRoute
  '/purchasing/bills': typeof AppPurchasingBillsRouteWithChildren
  '/purchasing/orders': typeof AppPurchasingOrdersRouteWithChildren
  '/purchasing/suppliers': typeof AppPurchasingSuppliersRoute
  '/sales/customers': typeof AppSalesCustomersRoute
  '/sales/invoices': typeof AppSalesInvoicesRouteWithChildren
  '/sales/orders': typeof AppSalesOrdersRouteWithChildren
  '/sales/quotations': typeof AppSalesQuotationsRouteWithChildren
  '/accounting/': typeof AppAccountingIndexRoute
  '/hrm/': typeof AppHrmIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/purchasing/': typeof AppPurchasingIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/hrm/leave/new': typeof AppHrmLeaveNewRoute
  '/inventory/products/$productId': typeof AppInventoryProductsProductIdRoute
  '/purchasing/bills/$billId': typeof AppPurchasingBillsBillIdRoute
  '/purchasing/bills/new': typeof AppPurchasingBillsNewRoute
  '/purchasing/orders/new': typeof AppPurchasingOrdersNewRoute
  '/sales/quotations/$quotationId': typeof AppSalesQuotationsQuotationIdRoute
  '/sales/quotations/new': typeof AppSalesQuotationsNewRoute
  '/hrm/leave/': typeof AppHrmLeaveIndexRoute
  '/inventory/products/': typeof AppInventoryProductsIndexRoute
  '/purchasing/bills/': typeof AppPurchasingBillsIndexRoute
  '/purchasing/orders/': typeof AppPurchasingOrdersIndexRoute
  '/sales/invoices/': typeof AppSalesInvoicesIndexRoute
  '/sales/orders/': typeof AppSalesOrdersIndexRoute
  '/sales/quotations/': typeof AppSalesQuotationsIndexRoute
  '/hrm/leave/$leaveId/edit': typeof AppHrmLeaveLeaveIdEditRoute
  '/purchasing/orders/$poId/receive': typeof AppPurchasingOrdersPoIdReceiveRoute
  '/sales/invoices/$invoiceId/preview': typeof AppSalesInvoicesInvoiceIdPreviewRoute
  '/sales/orders/$soId/deliver': typeof AppSalesOrdersSoIdDeliverRoute
  '/hrm/leave/$leaveId/': typeof AppHrmLeaveLeaveIdIndexRoute
  '/purchasing/orders/$poId/': typeof AppPurchasingOrdersPoIdIndexRoute
  '/sales/invoices/$invoiceId/': typeof AppSalesInvoicesInvoiceIdIndexRoute
  '/sales/orders/$soId/': typeof AppSalesOrdersSoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/403': typeof App403Route
  '/admin': typeof AppAdminRoute
  '/approvals': typeof AppApprovalsRoute
  '/login': typeof AuthLoginRoute
  '/accounting/ap-aging': typeof AppAccountingApAgingRoute
  '/accounting/ar-aging': typeof AppAccountingArAgingRoute
  '/accounting/chart-of-accounts': typeof AppAccountingChartOfAccountsRoute
  '/accounting/general-ledger': typeof AppAccountingGeneralLedgerRoute
  '/accounting/trial-balance': typeof AppAccountingTrialBalanceRoute
  '/inventory/stock-levels': typeof AppInventoryStockLevelsRoute
  '/inventory/stock-movements': typeof AppInventoryStockMovementsRoute
  '/purchasing/suppliers': typeof AppPurchasingSuppliersRoute
  '/sales/customers': typeof AppSalesCustomersRoute
  '/accounting': typeof AppAccountingIndexRoute
  '/hrm': typeof AppHrmIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/purchasing': typeof AppPurchasingIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/hrm/leave/new': typeof AppHrmLeaveNewRoute
  '/inventory/products/$productId': typeof AppInventoryProductsProductIdRoute
  '/purchasing/bills/$billId': typeof AppPurchasingBillsBillIdRoute
  '/purchasing/bills/new': typeof AppPurchasingBillsNewRoute
  '/purchasing/orders/new': typeof AppPurchasingOrdersNewRoute
  '/sales/quotations/$quotationId': typeof AppSalesQuotationsQuotationIdRoute
  '/sales/quotations/new': typeof AppSalesQuotationsNewRoute
  '/hrm/leave': typeof AppHrmLeaveIndexRoute
  '/inventory/products': typeof AppInventoryProductsIndexRoute
  '/purchasing/bills': typeof AppPurchasingBillsIndexRoute
  '/purchasing/orders': typeof AppPurchasingOrdersIndexRoute
  '/sales/invoices': typeof AppSalesInvoicesIndexRoute
  '/sales/orders': typeof AppSalesOrdersIndexRoute
  '/sales/quotations': typeof AppSalesQuotationsIndexRoute
  '/hrm/leave/$leaveId/edit': typeof AppHrmLeaveLeaveIdEditRoute
  '/purchasing/orders/$poId/receive': typeof AppPurchasingOrdersPoIdReceiveRoute
  '/sales/invoices/$invoiceId/preview': typeof AppSalesInvoicesInvoiceIdPreviewRoute
  '/sales/orders/$soId/deliver': typeof AppSalesOrdersSoIdDeliverRoute
  '/hrm/leave/$leaveId': typeof AppHrmLeaveLeaveIdIndexRoute
  '/purchasing/orders/$poId': typeof AppPurchasingOrdersPoIdIndexRoute
  '/sales/invoices/$invoiceId': typeof AppSalesInvoicesInvoiceIdIndexRoute
  '/sales/orders/$soId': typeof AppSalesOrdersSoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/403': typeof App403Route
  '/_app/accounting': typeof AppAccountingRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/hrm': typeof AppHrmRouteWithChildren
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/purchasing': typeof AppPurchasingRouteWithChildren
  '/_app/sales': typeof AppSalesRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounting/ap-aging': typeof AppAccountingApAgingRoute
  '/_app/accounting/ar-aging': typeof AppAccountingArAgingRoute
  '/_app/accounting/chart-of-accounts': typeof AppAccountingChartOfAccountsRoute
  '/_app/accounting/general-ledger': typeof AppAccountingGeneralLedgerRoute
  '/_app/accounting/trial-balance': typeof AppAccountingTrialBalanceRoute
  '/_app/hrm/leave': typeof AppHrmLeaveRouteWithChildren
  '/_app/inventory/products': typeof AppInventoryProductsRouteWithChildren
  '/_app/inventory/stock-levels': typeof AppInventoryStockLevelsRoute
  '/_app/inventory/stock-movements': typeof AppInventoryStockMovementsRoute
  '/_app/purchasing/bills': typeof AppPurchasingBillsRouteWithChildren
  '/_app/purchasing/orders': typeof AppPurchasingOrdersRouteWithChildren
  '/_app/purchasing/suppliers': typeof AppPurchasingSuppliersRoute
  '/_app/sales/customers': typeof AppSalesCustomersRoute
  '/_app/sales/invoices': typeof AppSalesInvoicesRouteWithChildren
  '/_app/sales/orders': typeof AppSalesOrdersRouteWithChildren
  '/_app/sales/quotations': typeof AppSalesQuotationsRouteWithChildren
  '/_app/accounting/': typeof AppAccountingIndexRoute
  '/_app/hrm/': typeof AppHrmIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/purchasing/': typeof AppPurchasingIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/hrm/leave/new': typeof AppHrmLeaveNewRoute
  '/_app/inventory/products/$productId': typeof AppInventoryProductsProductIdRoute
  '/_app/purchasing/bills/$billId': typeof AppPurchasingBillsBillIdRoute
  '/_app/purchasing/bills/new': typeof AppPurchasingBillsNewRoute
  '/_app/purchasing/orders/new': typeof AppPurchasingOrdersNewRoute
  '/_app/sales/quotations/$quotationId': typeof AppSalesQuotationsQuotationIdRoute
  '/_app/sales/quotations/new': typeof AppSalesQuotationsNewRoute
  '/_app/hrm/leave/': typeof AppHrmLeaveIndexRoute
  '/_app/inventory/products/': typeof AppInventoryProductsIndexRoute
  '/_app/purchasing/bills/': typeof AppPurchasingBillsIndexRoute
  '/_app/purchasing/orders/': typeof AppPurchasingOrdersIndexRoute
  '/_app/sales/invoices/': typeof AppSalesInvoicesIndexRoute
  '/_app/sales/orders/': typeof AppSalesOrdersIndexRoute
  '/_app/sales/quotations/': typeof AppSalesQuotationsIndexRoute
  '/_app/hrm/leave/$leaveId/edit': typeof AppHrmLeaveLeaveIdEditRoute
  '/_app/purchasing/orders/$poId/receive': typeof AppPurchasingOrdersPoIdReceiveRoute
  '/_app/sales/invoices/$invoiceId/preview': typeof AppSalesInvoicesInvoiceIdPreviewRoute
  '/_app/sales/orders/$soId/deliver': typeof AppSalesOrdersSoIdDeliverRoute
  '/_app/hrm/leave/$leaveId/': typeof AppHrmLeaveLeaveIdIndexRoute
  '/_app/purchasing/orders/$poId/': typeof AppPurchasingOrdersPoIdIndexRoute
  '/_app/sales/invoices/$invoiceId/': typeof AppSalesInvoicesInvoiceIdIndexRoute
  '/_app/sales/orders/$soId/': typeof AppSalesOrdersSoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/accounting'
    | '/admin'
    | '/approvals'
    | '/hrm'
    | '/inventory'
    | '/purchasing'
    | '/sales'
    | '/login'
    | '/accounting/ap-aging'
    | '/accounting/ar-aging'
    | '/accounting/chart-of-accounts'
    | '/accounting/general-ledger'
    | '/accounting/trial-balance'
    | '/hrm/leave'
    | '/inventory/products'
    | '/inventory/stock-levels'
    | '/inventory/stock-movements'
    | '/purchasing/bills'
    | '/purchasing/orders'
    | '/purchasing/suppliers'
    | '/sales/customers'
    | '/sales/invoices'
    | '/sales/orders'
    | '/sales/quotations'
    | '/accounting/'
    | '/hrm/'
    | '/inventory/'
    | '/purchasing/'
    | '/sales/'
    | '/hrm/leave/new'
    | '/inventory/products/$productId'
    | '/purchasing/bills/$billId'
    | '/purchasing/bills/new'
    | '/purchasing/orders/new'
    | '/sales/quotations/$quotationId'
    | '/sales/quotations/new'
    | '/hrm/leave/'
    | '/inventory/products/'
    | '/purchasing/bills/'
    | '/purchasing/orders/'
    | '/sales/invoices/'
    | '/sales/orders/'
    | '/sales/quotations/'
    | '/hrm/leave/$leaveId/edit'
    | '/purchasing/orders/$poId/receive'
    | '/sales/invoices/$invoiceId/preview'
    | '/sales/orders/$soId/deliver'
    | '/hrm/leave/$leaveId/'
    | '/purchasing/orders/$poId/'
    | '/sales/invoices/$invoiceId/'
    | '/sales/orders/$soId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/admin'
    | '/approvals'
    | '/login'
    | '/accounting/ap-aging'
    | '/accounting/ar-aging'
    | '/accounting/chart-of-accounts'
    | '/accounting/general-ledger'
    | '/accounting/trial-balance'
    | '/inventory/stock-levels'
    | '/inventory/stock-movements'
    | '/purchasing/suppliers'
    | '/sales/customers'
    | '/accounting'
    | '/hrm'
    | '/inventory'
    | '/purchasing'
    | '/sales'
    | '/hrm/leave/new'
    | '/inventory/products/$productId'
    | '/purchasing/bills/$billId'
    | '/purchasing/bills/new'
    | '/purchasing/orders/new'
    | '/sales/quotations/$quotationId'
    | '/sales/quotations/new'
    | '/hrm/leave'
    | '/inventory/products'
    | '/purchasing/bills'
    | '/purchasing/orders'
    | '/sales/invoices'
    | '/sales/orders'
    | '/sales/quotations'
    | '/hrm/leave/$leaveId/edit'
    | '/purchasing/orders/$poId/receive'
    | '/sales/invoices/$invoiceId/preview'
    | '/sales/orders/$soId/deliver'
    | '/hrm/leave/$leaveId'
    | '/purchasing/orders/$poId'
    | '/sales/invoices/$invoiceId'
    | '/sales/orders/$soId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/403'
    | '/_app/accounting'
    | '/_app/admin'
    | '/_app/approvals'
    | '/_app/hrm'
    | '/_app/inventory'
    | '/_app/purchasing'
    | '/_app/sales'
    | '/_auth/login'
    | '/_app/'
    | '/_app/accounting/ap-aging'
    | '/_app/accounting/ar-aging'
    | '/_app/accounting/chart-of-accounts'
    | '/_app/accounting/general-ledger'
    | '/_app/accounting/trial-balance'
    | '/_app/hrm/leave'
    | '/_app/inventory/products'
    | '/_app/inventory/stock-levels'
    | '/_app/inventory/stock-movements'
    | '/_app/purchasing/bills'
    | '/_app/purchasing/orders'
    | '/_app/purchasing/suppliers'
    | '/_app/sales/customers'
    | '/_app/sales/invoices'
    | '/_app/sales/orders'
    | '/_app/sales/quotations'
    | '/_app/accounting/'
    | '/_app/hrm/'
    | '/_app/inventory/'
    | '/_app/purchasing/'
    | '/_app/sales/'
    | '/_app/hrm/leave/new'
    | '/_app/inventory/products/$productId'
    | '/_app/purchasing/bills/$billId'
    | '/_app/purchasing/bills/new'
    | '/_app/purchasing/orders/new'
    | '/_app/sales/quotations/$quotationId'
    | '/_app/sales/quotations/new'
    | '/_app/hrm/leave/'
    | '/_app/inventory/products/'
    | '/_app/purchasing/bills/'
    | '/_app/purchasing/orders/'
    | '/_app/sales/invoices/'
    | '/_app/sales/orders/'
    | '/_app/sales/quotations/'
    | '/_app/hrm/leave/$leaveId/edit'
    | '/_app/purchasing/orders/$poId/receive'
    | '/_app/sales/invoices/$invoiceId/preview'
    | '/_app/sales/orders/$soId/deliver'
    | '/_app/hrm/leave/$leaveId/'
    | '/_app/purchasing/orders/$poId/'
    | '/_app/sales/invoices/$invoiceId/'
    | '/_app/sales/orders/$soId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/403': {
      id: '/_app/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof App403RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hrm': {
      id: '/_app/hrm'
      path: '/hrm'
      fullPath: '/hrm'
      preLoaderRoute: typeof AppHrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchasing': {
      id: '/_app/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof AppPurchasingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/accounting/': {
      id: '/_app/accounting/'
      path: '/'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AppAccountingIndexRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/ap-aging': {
      id: '/_app/accounting/ap-aging'
      path: '/ap-aging'
      fullPath: '/accounting/ap-aging'
      preLoaderRoute: typeof AppAccountingApAgingRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/ar-aging': {
      id: '/_app/accounting/ar-aging'
      path: '/ar-aging'
      fullPath: '/accounting/ar-aging'
      preLoaderRoute: typeof AppAccountingArAgingRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/chart-of-accounts': {
      id: '/_app/accounting/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/accounting/chart-of-accounts'
      preLoaderRoute: typeof AppAccountingChartOfAccountsRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/general-ledger': {
      id: '/_app/accounting/general-ledger'
      path: '/general-ledger'
      fullPath: '/accounting/general-ledger'
      preLoaderRoute: typeof AppAccountingGeneralLedgerRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/trial-balance': {
      id: '/_app/accounting/trial-balance'
      path: '/trial-balance'
      fullPath: '/accounting/trial-balance'
      preLoaderRoute: typeof AppAccountingTrialBalanceRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/hrm/': {
      id: '/_app/hrm/'
      path: '/'
      fullPath: '/hrm/'
      preLoaderRoute: typeof AppHrmIndexRouteImport
      parentRoute: typeof AppHrmRoute
    }
    '/_app/hrm/leave': {
      id: '/_app/hrm/leave'
      path: '/leave'
      fullPath: '/hrm/leave'
      preLoaderRoute: typeof AppHrmLeaveRouteImport
      parentRoute: typeof AppHrmRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/products': {
      id: '/_app/inventory/products'
      path: '/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof AppInventoryProductsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/stock-levels': {
      id: '/_app/inventory/stock-levels'
      path: '/stock-levels'
      fullPath: '/inventory/stock-levels'
      preLoaderRoute: typeof AppInventoryStockLevelsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/stock-movements': {
      id: '/_app/inventory/stock-movements'
      path: '/stock-movements'
      fullPath: '/inventory/stock-movements'
      preLoaderRoute: typeof AppInventoryStockMovementsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/purchasing/': {
      id: '/_app/purchasing/'
      path: '/'
      fullPath: '/purchasing/'
      preLoaderRoute: typeof AppPurchasingIndexRouteImport
      parentRoute: typeof AppPurchasingRoute
    }
    '/_app/purchasing/bills': {
      id: '/_app/purchasing/bills'
      path: '/bills'
      fullPath: '/purchasing/bills'
      preLoaderRoute: typeof AppPurchasingBillsRouteImport
      parentRoute: typeof AppPurchasingRoute
    }
    '/_app/purchasing/orders': {
      id: '/_app/purchasing/orders'
      path: '/orders'
      fullPath: '/purchasing/orders'
      preLoaderRoute: typeof AppPurchasingOrdersRouteImport
      parentRoute: typeof AppPurchasingRoute
    }
    '/_app/purchasing/suppliers': {
      id: '/_app/purchasing/suppliers'
      path: '/suppliers'
      fullPath: '/purchasing/suppliers'
      preLoaderRoute: typeof AppPurchasingSuppliersRouteImport
      parentRoute: typeof AppPurchasingRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/customers': {
      id: '/_app/sales/customers'
      path: '/customers'
      fullPath: '/sales/customers'
      preLoaderRoute: typeof AppSalesCustomersRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/invoices': {
      id: '/_app/sales/invoices'
      path: '/invoices'
      fullPath: '/sales/invoices'
      preLoaderRoute: typeof AppSalesInvoicesRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/orders': {
      id: '/_app/sales/orders'
      path: '/orders'
      fullPath: '/sales/orders'
      preLoaderRoute: typeof AppSalesOrdersRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/quotations': {
      id: '/_app/sales/quotations'
      path: '/quotations'
      fullPath: '/sales/quotations'
      preLoaderRoute: typeof AppSalesQuotationsRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/hrm/leave/': {
      id: '/_app/hrm/leave/'
      path: '/'
      fullPath: '/hrm/leave/'
      preLoaderRoute: typeof AppHrmLeaveIndexRouteImport
      parentRoute: typeof AppHrmLeaveRoute
    }
    '/_app/hrm/leave/new': {
      id: '/_app/hrm/leave/new'
      path: '/new'
      fullPath: '/hrm/leave/new'
      preLoaderRoute: typeof AppHrmLeaveNewRouteImport
      parentRoute: typeof AppHrmLeaveRoute
    }
    '/_app/inventory/products/': {
      id: '/_app/inventory/products/'
      path: '/'
      fullPath: '/inventory/products/'
      preLoaderRoute: typeof AppInventoryProductsIndexRouteImport
      parentRoute: typeof AppInventoryProductsRoute
    }
    '/_app/inventory/products/$productId': {
      id: '/_app/inventory/products/$productId'
      path: '/$productId'
      fullPath: '/inventory/products/$productId'
      preLoaderRoute: typeof AppInventoryProductsProductIdRouteImport
      parentRoute: typeof AppInventoryProductsRoute
    }
    '/_app/purchasing/bills/': {
      id: '/_app/purchasing/bills/'
      path: '/'
      fullPath: '/purchasing/bills/'
      preLoaderRoute: typeof AppPurchasingBillsIndexRouteImport
      parentRoute: typeof AppPurchasingBillsRoute
    }
    '/_app/purchasing/bills/$billId': {
      id: '/_app/purchasing/bills/$billId'
      path: '/$billId'
      fullPath: '/purchasing/bills/$billId'
      preLoaderRoute: typeof AppPurchasingBillsBillIdRouteImport
      parentRoute: typeof AppPurchasingBillsRoute
    }
    '/_app/purchasing/bills/new': {
      id: '/_app/purchasing/bills/new'
      path: '/new'
      fullPath: '/purchasing/bills/new'
      preLoaderRoute: typeof AppPurchasingBillsNewRouteImport
      parentRoute: typeof AppPurchasingBillsRoute
    }
    '/_app/purchasing/orders/': {
      id: '/_app/purchasing/orders/'
      path: '/'
      fullPath: '/purchasing/orders/'
      preLoaderRoute: typeof AppPurchasingOrdersIndexRouteImport
      parentRoute: typeof AppPurchasingOrdersRoute
    }
    '/_app/purchasing/orders/new': {
      id: '/_app/purchasing/orders/new'
      path: '/new'
      fullPath: '/purchasing/orders/new'
      preLoaderRoute: typeof AppPurchasingOrdersNewRouteImport
      parentRoute: typeof AppPurchasingOrdersRoute
    }
    '/_app/sales/invoices/': {
      id: '/_app/sales/invoices/'
      path: '/'
      fullPath: '/sales/invoices/'
      preLoaderRoute: typeof AppSalesInvoicesIndexRouteImport
      parentRoute: typeof AppSalesInvoicesRoute
    }
    '/_app/sales/orders/': {
      id: '/_app/sales/orders/'
      path: '/'
      fullPath: '/sales/orders/'
      preLoaderRoute: typeof AppSalesOrdersIndexRouteImport
      parentRoute: typeof AppSalesOrdersRoute
    }
    '/_app/sales/quotations/': {
      id: '/_app/sales/quotations/'
      path: '/'
      fullPath: '/sales/quotations/'
      preLoaderRoute: typeof AppSalesQuotationsIndexRouteImport
      parentRoute: typeof AppSalesQuotationsRoute
    }
    '/_app/sales/quotations/$quotationId': {
      id: '/_app/sales/quotations/$quotationId'
      path: '/$quotationId'
      fullPath: '/sales/quotations/$quotationId'
      preLoaderRoute: typeof AppSalesQuotationsQuotationIdRouteImport
      parentRoute: typeof AppSalesQuotationsRoute
    }
    '/_app/sales/quotations/new': {
      id: '/_app/sales/quotations/new'
      path: '/new'
      fullPath: '/sales/quotations/new'
      preLoaderRoute: typeof AppSalesQuotationsNewRouteImport
      parentRoute: typeof AppSalesQuotationsRoute
    }
    '/_app/hrm/leave/$leaveId/': {
      id: '/_app/hrm/leave/$leaveId/'
      path: '/$leaveId'
      fullPath: '/hrm/leave/$leaveId/'
      preLoaderRoute: typeof AppHrmLeaveLeaveIdIndexRouteImport
      parentRoute: typeof AppHrmLeaveRoute
    }
    '/_app/hrm/leave/$leaveId/edit': {
      id: '/_app/hrm/leave/$leaveId/edit'
      path: '/$leaveId/edit'
      fullPath: '/hrm/leave/$leaveId/edit'
      preLoaderRoute: typeof AppHrmLeaveLeaveIdEditRouteImport
      parentRoute: typeof AppHrmLeaveRoute
    }
    '/_app/purchasing/orders/$poId/': {
      id: '/_app/purchasing/orders/$poId/'
      path: '/$poId'
      fullPath: '/purchasing/orders/$poId/'
      preLoaderRoute: typeof AppPurchasingOrdersPoIdIndexRouteImport
      parentRoute: typeof AppPurchasingOrdersRoute
    }
    '/_app/purchasing/orders/$poId/receive': {
      id: '/_app/purchasing/orders/$poId/receive'
      path: '/$poId/receive'
      fullPath: '/purchasing/orders/$poId/receive'
      preLoaderRoute: typeof AppPurchasingOrdersPoIdReceiveRouteImport
      parentRoute: typeof AppPurchasingOrdersRoute
    }
    '/_app/sales/invoices/$invoiceId/': {
      id: '/_app/sales/invoices/$invoiceId/'
      path: '/$invoiceId'
      fullPath: '/sales/invoices/$invoiceId/'
      preLoaderRoute: typeof AppSalesInvoicesInvoiceIdIndexRouteImport
      parentRoute: typeof AppSalesInvoicesRoute
    }
    '/_app/sales/invoices/$invoiceId/preview': {
      id: '/_app/sales/invoices/$invoiceId/preview'
      path: '/$invoiceId/preview'
      fullPath: '/sales/invoices/$invoiceId/preview'
      preLoaderRoute: typeof AppSalesInvoicesInvoiceIdPreviewRouteImport
      parentRoute: typeof AppSalesInvoicesRoute
    }
    '/_app/sales/orders/$soId/': {
      id: '/_app/sales/orders/$soId/'
      path: '/$soId'
      fullPath: '/sales/orders/$soId/'
      preLoaderRoute: typeof AppSalesOrdersSoIdIndexRouteImport
      parentRoute: typeof AppSalesOrdersRoute
    }
    '/_app/sales/orders/$soId/deliver': {
      id: '/_app/sales/orders/$soId/deliver'
      path: '/$soId/deliver'
      fullPath: '/sales/orders/$soId/deliver'
      preLoaderRoute: typeof AppSalesOrdersSoIdDeliverRouteImport
      parentRoute: typeof AppSalesOrdersRoute
    }
  }
}

interface AppAccountingRouteChildren {
  AppAccountingApAgingRoute: typeof AppAccountingApAgingRoute
  AppAccountingArAgingRoute: typeof AppAccountingArAgingRoute
  AppAccountingChartOfAccountsRoute: typeof AppAccountingChartOfAccountsRoute
  AppAccountingGeneralLedgerRoute: typeof AppAccountingGeneralLedgerRoute
  AppAccountingTrialBalanceRoute: typeof AppAccountingTrialBalanceRoute
  AppAccountingIndexRoute: typeof AppAccountingIndexRoute
}

const AppAccountingRouteChildren: AppAccountingRouteChildren = {
  AppAccountingApAgingRoute: AppAccountingApAgingRoute,
  AppAccountingArAgingRoute: AppAccountingArAgingRoute,
  AppAccountingChartOfAccountsRoute: AppAccountingChartOfAccountsRoute,
  AppAccountingGeneralLedgerRoute: AppAccountingGeneralLedgerRoute,
  AppAccountingTrialBalanceRoute: AppAccountingTrialBalanceRoute,
  AppAccountingIndexRoute: AppAccountingIndexRoute,
}

const AppAccountingRouteWithChildren = AppAccountingRoute._addFileChildren(
  AppAccountingRouteChildren,
)

interface AppHrmLeaveRouteChildren {
  AppHrmLeaveNewRoute: typeof AppHrmLeaveNewRoute
  AppHrmLeaveIndexRoute: typeof AppHrmLeaveIndexRoute
  AppHrmLeaveLeaveIdEditRoute: typeof AppHrmLeaveLeaveIdEditRoute
  AppHrmLeaveLeaveIdIndexRoute: typeof AppHrmLeaveLeaveIdIndexRoute
}

const AppHrmLeaveRouteChildren: AppHrmLeaveRouteChildren = {
  AppHrmLeaveNewRoute: AppHrmLeaveNewRoute,
  AppHrmLeaveIndexRoute: AppHrmLeaveIndexRoute,
  AppHrmLeaveLeaveIdEditRoute: AppHrmLeaveLeaveIdEditRoute,
  AppHrmLeaveLeaveIdIndexRoute: AppHrmLeaveLeaveIdIndexRoute,
}

const AppHrmLeaveRouteWithChildren = AppHrmLeaveRoute._addFileChildren(
  AppHrmLeaveRouteChildren,
)

interface AppHrmRouteChildren {
  AppHrmLeaveRoute: typeof AppHrmLeaveRouteWithChildren
  AppHrmIndexRoute: typeof AppHrmIndexRoute
}

const AppHrmRouteChildren: AppHrmRouteChildren = {
  AppHrmLeaveRoute: AppHrmLeaveRouteWithChildren,
  AppHrmIndexRoute: AppHrmIndexRoute,
}

const AppHrmRouteWithChildren =
  AppHrmRoute._addFileChildren(AppHrmRouteChildren)

interface AppInventoryProductsRouteChildren {
  AppInventoryProductsProductIdRoute: typeof AppInventoryProductsProductIdRoute
  AppInventoryProductsIndexRoute: typeof AppInventoryProductsIndexRoute
}

const AppInventoryProductsRouteChildren: AppInventoryProductsRouteChildren = {
  AppInventoryProductsProductIdRoute: AppInventoryProductsProductIdRoute,
  AppInventoryProductsIndexRoute: AppInventoryProductsIndexRoute,
}

const AppInventoryProductsRouteWithChildren =
  AppInventoryProductsRoute._addFileChildren(AppInventoryProductsRouteChildren)

interface AppInventoryRouteChildren {
  AppInventoryProductsRoute: typeof AppInventoryProductsRouteWithChildren
  AppInventoryStockLevelsRoute: typeof AppInventoryStockLevelsRoute
  AppInventoryStockMovementsRoute: typeof AppInventoryStockMovementsRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryProductsRoute: AppInventoryProductsRouteWithChildren,
  AppInventoryStockLevelsRoute: AppInventoryStockLevelsRoute,
  AppInventoryStockMovementsRoute: AppInventoryStockMovementsRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppPurchasingBillsRouteChildren {
  AppPurchasingBillsBillIdRoute: typeof AppPurchasingBillsBillIdRoute
  AppPurchasingBillsNewRoute: typeof AppPurchasingBillsNewRoute
  AppPurchasingBillsIndexRoute: typeof AppPurchasingBillsIndexRoute
}

const AppPurchasingBillsRouteChildren: AppPurchasingBillsRouteChildren = {
  AppPurchasingBillsBillIdRoute: AppPurchasingBillsBillIdRoute,
  AppPurchasingBillsNewRoute: AppPurchasingBillsNewRoute,
  AppPurchasingBillsIndexRoute: AppPurchasingBillsIndexRoute,
}

const AppPurchasingBillsRouteWithChildren =
  AppPurchasingBillsRoute._addFileChildren(AppPurchasingBillsRouteChildren)

interface AppPurchasingOrdersRouteChildren {
  AppPurchasingOrdersNewRoute: typeof AppPurchasingOrdersNewRoute
  AppPurchasingOrdersIndexRoute: typeof AppPurchasingOrdersIndexRoute
  AppPurchasingOrdersPoIdReceiveRoute: typeof AppPurchasingOrdersPoIdReceiveRoute
  AppPurchasingOrdersPoIdIndexRoute: typeof AppPurchasingOrdersPoIdIndexRoute
}

const AppPurchasingOrdersRouteChildren: AppPurchasingOrdersRouteChildren = {
  AppPurchasingOrdersNewRoute: AppPurchasingOrdersNewRoute,
  AppPurchasingOrdersIndexRoute: AppPurchasingOrdersIndexRoute,
  AppPurchasingOrdersPoIdReceiveRoute: AppPurchasingOrdersPoIdReceiveRoute,
  AppPurchasingOrdersPoIdIndexRoute: AppPurchasingOrdersPoIdIndexRoute,
}

const AppPurchasingOrdersRouteWithChildren =
  AppPurchasingOrdersRoute._addFileChildren(AppPurchasingOrdersRouteChildren)

interface AppPurchasingRouteChildren {
  AppPurchasingBillsRoute: typeof AppPurchasingBillsRouteWithChildren
  AppPurchasingOrdersRoute: typeof AppPurchasingOrdersRouteWithChildren
  AppPurchasingSuppliersRoute: typeof AppPurchasingSuppliersRoute
  AppPurchasingIndexRoute: typeof AppPurchasingIndexRoute
}

const AppPurchasingRouteChildren: AppPurchasingRouteChildren = {
  AppPurchasingBillsRoute: AppPurchasingBillsRouteWithChildren,
  AppPurchasingOrdersRoute: AppPurchasingOrdersRouteWithChildren,
  AppPurchasingSuppliersRoute: AppPurchasingSuppliersRoute,
  AppPurchasingIndexRoute: AppPurchasingIndexRoute,
}

const AppPurchasingRouteWithChildren = AppPurchasingRoute._addFileChildren(
  AppPurchasingRouteChildren,
)

interface AppSalesInvoicesRouteChildren {
  AppSalesInvoicesIndexRoute: typeof AppSalesInvoicesIndexRoute
  AppSalesInvoicesInvoiceIdPreviewRoute: typeof AppSalesInvoicesInvoiceIdPreviewRoute
  AppSalesInvoicesInvoiceIdIndexRoute: typeof AppSalesInvoicesInvoiceIdIndexRoute
}

const AppSalesInvoicesRouteChildren: AppSalesInvoicesRouteChildren = {
  AppSalesInvoicesIndexRoute: AppSalesInvoicesIndexRoute,
  AppSalesInvoicesInvoiceIdPreviewRoute: AppSalesInvoicesInvoiceIdPreviewRoute,
  AppSalesInvoicesInvoiceIdIndexRoute: AppSalesInvoicesInvoiceIdIndexRoute,
}

const AppSalesInvoicesRouteWithChildren =
  AppSalesInvoicesRoute._addFileChildren(AppSalesInvoicesRouteChildren)

interface AppSalesOrdersRouteChildren {
  AppSalesOrdersIndexRoute: typeof AppSalesOrdersIndexRoute
  AppSalesOrdersSoIdDeliverRoute: typeof AppSalesOrdersSoIdDeliverRoute
  AppSalesOrdersSoIdIndexRoute: typeof AppSalesOrdersSoIdIndexRoute
}

const AppSalesOrdersRouteChildren: AppSalesOrdersRouteChildren = {
  AppSalesOrdersIndexRoute: AppSalesOrdersIndexRoute,
  AppSalesOrdersSoIdDeliverRoute: AppSalesOrdersSoIdDeliverRoute,
  AppSalesOrdersSoIdIndexRoute: AppSalesOrdersSoIdIndexRoute,
}

const AppSalesOrdersRouteWithChildren = AppSalesOrdersRoute._addFileChildren(
  AppSalesOrdersRouteChildren,
)

interface AppSalesQuotationsRouteChildren {
  AppSalesQuotationsQuotationIdRoute: typeof AppSalesQuotationsQuotationIdRoute
  AppSalesQuotationsNewRoute: typeof AppSalesQuotationsNewRoute
  AppSalesQuotationsIndexRoute: typeof AppSalesQuotationsIndexRoute
}

const AppSalesQuotationsRouteChildren: AppSalesQuotationsRouteChildren = {
  AppSalesQuotationsQuotationIdRoute: AppSalesQuotationsQuotationIdRoute,
  AppSalesQuotationsNewRoute: AppSalesQuotationsNewRoute,
  AppSalesQuotationsIndexRoute: AppSalesQuotationsIndexRoute,
}

const AppSalesQuotationsRouteWithChildren =
  AppSalesQuotationsRoute._addFileChildren(AppSalesQuotationsRouteChildren)

interface AppSalesRouteChildren {
  AppSalesCustomersRoute: typeof AppSalesCustomersRoute
  AppSalesInvoicesRoute: typeof AppSalesInvoicesRouteWithChildren
  AppSalesOrdersRoute: typeof AppSalesOrdersRouteWithChildren
  AppSalesQuotationsRoute: typeof AppSalesQuotationsRouteWithChildren
  AppSalesIndexRoute: typeof AppSalesIndexRoute
}

const AppSalesRouteChildren: AppSalesRouteChildren = {
  AppSalesCustomersRoute: AppSalesCustomersRoute,
  AppSalesInvoicesRoute: AppSalesInvoicesRouteWithChildren,
  AppSalesOrdersRoute: AppSalesOrdersRouteWithChildren,
  AppSalesQuotationsRoute: AppSalesQuotationsRouteWithChildren,
  AppSalesIndexRoute: AppSalesIndexRoute,
}

const AppSalesRouteWithChildren = AppSalesRoute._addFileChildren(
  AppSalesRouteChildren,
)

interface AppRouteChildren {
  App403Route: typeof App403Route
  AppAccountingRoute: typeof AppAccountingRouteWithChildren
  AppAdminRoute: typeof AppAdminRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppHrmRoute: typeof AppHrmRouteWithChildren
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppPurchasingRoute: typeof AppPurchasingRouteWithChildren
  AppSalesRoute: typeof AppSalesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  App403Route: App403Route,
  AppAccountingRoute: AppAccountingRouteWithChildren,
  AppAdminRoute: AppAdminRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppHrmRoute: AppHrmRouteWithChildren,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppPurchasingRoute: AppPurchasingRouteWithChildren,
  AppSalesRoute: AppSalesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
